### ISSUE TITLE
Selection possible d'une couleur par catégorie

### ISSUE THREAD

**Issue by alain01** [GregMage/xmdoc#13]
Possibilité de sélectionner une couleur pour chaque catégorie, comme cela est fait dans l'excellent module xmtutorial.
Evidemment, cela doit être intégré également dans les templates associés (index,  pages du document, blocs)

**Comment by GregMage** [comment]
https://github.com/GregMage/xmdoc/commit/e3b70475692750b917dda9f5ff6f7f5f76295cbd
