### ISSUE TITLE
PHP8 and xswatch4

### ISSUE THREAD

**Issue by mambax7** [GregMage/xmdoc#15]
in /modules/xmdoc/index.php

`Warning: Undefined array key "doc_cid_options" in file /xoops_data/caches/smarty_compile/da890def-xmdoc-xswatch4-default^%%6D^6DB^6DB0FB6A%%db%3Axmdoc_index.tpl.php line 77`

**Comment by mambax7** [comment]
in xbootstrap:
Warning: Undefined array key "doc_cid_options" in file /xoops_data/caches/smarty_compile/da890def-xmdoc-xbootstrap-default^%%6D^6DB^6DB0FB6A%%db%3Axmdoc_index.tpl.php line 56

**Comment by GregMage** [comment]
Now it's ok
