### ISSUE TITLE
Error : Smarty error

### ISSUE THREAD

**Issue by alain01** [GregMage/xmdoc#3]
Error : Smarty error: [in db:xmdoc_index.tpl line 21]: [plugin] modifier 'truncateHtml' is not implemented (core.load_plugins.php, line 118)

page http://localhost/modules/xmdoc/

**Comment by GregMage** [comment]
C'est normal, cette fonction est disponible uniquement avec xoops 2.5.10. Si tu veux faire des tests avec une version 2.5.9 il faut changer cette ligne:

`<{$document.description_short|truncateHtml:10:'...'}>`

Avec

<{$document.description_short|truncate:50:'...'}>

dans le fichier xmdoc_index.tpl ligne 21, 44, 69 et 94.
dans le fichier xmdoc_viewdoc.tpl ligne 11.
dans le fichier \blocks\xmdoc_block.tpl ligne 11.

Tu n'as pas tenu compte de l'avertissement sur la page d'index qui dit xoops 2.5.10 minimum ;-)

**Comment by alain01** [comment]
C'est vrai mais j'ai ceci en vert  : 
"coche verte valide"  Minimum XOOPS required: 2.5.10 (your version is 2.5.9) 
on devrait dans ce cas trouver en rouge l'image  l'image de la croix, et le texte en rouge ?

**Comment by GregMage** [comment]
Effectivement ce n'est pas normal. Je vais regarder pourquoi!

**Comment by GregMage** [comment]
Problème xoops 2.5.9. Ce message est généré automatiquement le problème est réglé dans xoops 2.5.10:

https://github.com/XOOPS/XoopsCore25/commit/381344edf6af8edb460e17c3b6094720b67f0ffe#diff-3d4b47567caec9cfaeb974d342a8753b

https://github.com/XOOPS/XoopsCore25/commit/412e924c21243ee38d34c7f063ea1dab8de548ed#diff-3d4b47567caec9cfaeb974d342a8753b

**Comment by alain01** [comment]
Mince, c'est embêtant ça.
Mais je ne comprends pas,
Avec un autre module avec une version pas assez haute, le message apparaît bien en rouge (xm-social)

**Comment by GregMage** [comment]
Ce n'est pas le même code.

Pour la version d'un module tu utilise:
`$moduleAdmin = Admin::getInstance();
$moduleAdmin->addConfigModuleVersion('system', 214);`

et pour xoops il faut mettre ceci dans xoopsversion.php du module:

`$modversion['min_xoops'] = '2.5.10';`

Deux manières de faire. En 2.5.9 le code qui gère la version de xoops n'arrive pas à gérer une version tel que X.Y.ZZ (2.5.10) avec 2 chiffres à la fin. C'est pour cela que l'affichage est faux.

Perso je travail toujours sur la version en développement de xoops ce qui me permet de tester xoops en même temps. Tu devrais faire pareil ça évite des problèmes avec les modules récents.
